server:
  port: 9090


spring:
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/horizon?serverTimezone=GMT%2b8
    username: root
    password: 123456
mybatis:
  mapper_locations: classpath:mapper/*.xml #扫描所以mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




